### ISSUE TITLE
Reporting error causes no movement of data, Report pdfs  will need to be created

### ISSUE THREAD

**Issue by CorinneBassin-SOI** [schmidtocean/sealog-server#6]
Current Cruise FKt241011 Dive 736, reports failed to build and so although all other exports ran successfully and were written to the local sealog /data/ folder, the code errors out before setting up the rsync to the cruise data since it exits at 

https://github.com/schmidtocean/sealog-server/blob/c419f75751b8ab5b1386312f8948a9a5ba0ea158/misc/sealog_vehicle_data_export_Sub.py#L805

Note: 
I temporarily forced sealog_vehicle_data_export_Sub.py to run and moved exports to the warehouse  but initially nothing was moved  after  dive tasks ran

1. Can we add a try to continue around this with a warning logged so that if everything else is created and only the reports error, the data still moves to the cruise data, thus making it available as soon as possible to scientists and allowing us to come back to deal with the missing reports?
2. Need to determine the issue that caused the report to fail, appears to not have been able to build the graph due to no nav data ... 
   a. can we fix this for this dive and re run?
  b. can we add better handling? 

```
RROR - index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/opt/sealog-server-Sub/./misc/sealog_vehicle_data_export_Sub.py", line 805, in <module>
    _build_lowering_reports(selected_cruise, selected_lowering)
  File "/opt/sealog-server-Sub/./misc/sealog_vehicle_data_export_Sub.py", line 542, in _build_lowering_reports
    raise(err)
  File "/opt/sealog-server-Sub/./misc/sealog_vehicle_data_export_Sub.py", line 537, in _build_lowering_reports
    file.write(lowering_summary_report.export_pdf())
  File "/opt/sealog-server-Sub/misc/reporting/sealog_build_lowering_summary_report.py", line 136, in export_pdf
    dive_track_filename = self._build_dive_track()
  File "/opt/sealog-server-Sub/misc/reporting/sealog_report_builder_Sub.py", line 1158, in _build_dive_track
    ax_dive_track.plot(lons[0], lats[0], linestyle='none', marker="o", markersize=12, alpha=0.6, c="green", markeredgecolor="black", markeredgewidth=1)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by KaarelRaeis-SOI** [comment]
The exports script was pretty hard to troubleshoot with a lot of repetitive permanent errors leading techs to elevate most issues.

1. filecrop lastline hack - downgraded this to INFO level, there was typically >100 lines of this message and to my understanding there is no user-actionable solutions
2. everything in try blocks
3. rsync error handling
4. subprocess.run instead of subprocess.call - more modern and gives output by default
5. implemented slackbot integration via webhooks - these exports can take considerable time to run thus there is a risk the outcome is not always checked, also supervisorD default view is not ideal for long messages and requires entering custom URL to see full output. Messages are grouped by ERROR/WARNING, repetitive messages are counted and displayed as 
```
• 20:26:06 - Could not process line: <ProductName>APG Atwood</ProductName>
(×54)WARNING - 
```

Currently testing in production

Outstanding:
- every dive claims NO WATCH CHANGE events but tables are built
- discuss with team whether more messages should be downgraded to INFO
- check/resolve when script does/should exit with success/error code

Current successful output:
![image](https://github.com/user-attachments/assets/87c7cb03-31f8-44b6-81b2-89dfced41566)

**Comment by KaarelRaeis-SOI** [comment]
All outstanding issues resolved, merged to main
